#ifndef STATES_H
#define STATES_H

#include <Arduino.h>

enum States {
  GROUND_IDLE = 1,
  LAUNCH_READY = 2,
  POWERED_ASCENT = 3,
  UNPOWERED_ASCENT = 4,
  SEPARATION = 5,
  PARACHUTE_DESCENT = 6,
  ROLL_CONTROL = 7,
  LANDING_DETECT = 8,
  MISSION_COMPLETE = 9,
  AVI_ERROR = 42
};

#endif