#ifndef SETTINGS_H
#define SETTINGS_H


// ! ALL COMMANDS NEED TO BE ENCLOSED BY <>

const String GOTO_LAUNCH_READY = "GOTO_LAUNCH_READY";
const String GOTO_POWERED_ASCENT = "GOTO_POWERED_ASCENT";
#endif